# Form implementation generated from reading ui file 'UltrasoundDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UltrasoundDialog(object):
    def setupUi(self, UltrasoundDialog):
        UltrasoundDialog.setObjectName("UltrasoundDialog")
        UltrasoundDialog.resize(270, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UltrasoundDialog.sizePolicy().hasHeightForWidth())
        UltrasoundDialog.setSizePolicy(sizePolicy)
        UltrasoundDialog.setMinimumSize(QtCore.QSize(270, 100))
        UltrasoundDialog.setMaximumSize(QtCore.QSize(270, 100))
        self.verticalLayout = QtWidgets.QVBoxLayout(UltrasoundDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(UltrasoundDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.signalFrequencyLine = QtWidgets.QLineEdit(UltrasoundDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalFrequencyLine.sizePolicy().hasHeightForWidth())
        self.signalFrequencyLine.setSizePolicy(sizePolicy)
        self.signalFrequencyLine.setMinimumSize(QtCore.QSize(150, 0))
        self.signalFrequencyLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.signalFrequencyLine.setObjectName("signalFrequencyLine")
        self.horizontalLayout.addWidget(self.signalFrequencyLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(UltrasoundDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.signalTimeLine = QtWidgets.QLineEdit(UltrasoundDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signalTimeLine.sizePolicy().hasHeightForWidth())
        self.signalTimeLine.setSizePolicy(sizePolicy)
        self.signalTimeLine.setMinimumSize(QtCore.QSize(150, 0))
        self.signalTimeLine.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.signalTimeLine.setObjectName("signalTimeLine")
        self.horizontalLayout_2.addWidget(self.signalTimeLine)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.dialogButtonBox = QtWidgets.QDialogButtonBox(UltrasoundDialog)
        self.dialogButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.dialogButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.dialogButtonBox.setCenterButtons(True)
        self.dialogButtonBox.setObjectName("dialogButtonBox")
        self.verticalLayout.addWidget(self.dialogButtonBox)

        self.retranslateUi(UltrasoundDialog)
        self.dialogButtonBox.accepted.connect(UltrasoundDialog.accept) # type: ignore
        self.dialogButtonBox.rejected.connect(UltrasoundDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UltrasoundDialog)

    def retranslateUi(self, UltrasoundDialog):
        _translate = QtCore.QCoreApplication.translate
        UltrasoundDialog.setWindowTitle(_translate("UltrasoundDialog", "Ultradound Dialog"))
        self.label.setText(_translate("UltrasoundDialog", "Частота сигналу"))
        self.label_2.setText(_translate("UltrasoundDialog", "Час сигналу (мс)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UltrasoundDialog = QtWidgets.QDialog()
    ui = Ui_UltrasoundDialog()
    ui.setupUi(UltrasoundDialog)
    UltrasoundDialog.show()
    sys.exit(app.exec())
