# Form implementation generated from reading ui file 'UltrasoundDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtWidgets
from PyQt6.QtWidgets import QDialog

from ui.raw.ui_ultrasounddialog import Ui_UltrasoundDialog


class UltrasoundDialog(QDialog, Ui_UltrasoundDialog):
	def __init__(self):
		super(UltrasoundDialog, self).__init__()
		self.setupUi(self)

		# Tracing dialog button clicks
		self.dialogButtonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Ok).clicked.connect(self.box_Ok_Clicked)
		self.dialogButtonBox.button(QtWidgets.QDialogButtonBox.StandardButton.Cancel).clicked.connect(self.box_Cancel_Clicked)

	def box_Ok_Clicked(self):
		self.done(QtWidgets.QDialogButtonBox.StandardButton.Ok.value)

	def box_Cancel_Clicked(self):
		self.done(QtWidgets.QDialogButtonBox.StandardButton.Cancel.value)
